# Generated by Django 6.0 on 2025-12-11 15:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(help_text='Ej: K1, T4, S1', max_length=20, unique=True)),
                ('es_cuatrimestral', models.BooleanField(default=False, help_text='Marcar si es un curso de Adultos (duración semestral)')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='academico.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('anio', models.IntegerField(default=2025)),
                ('periodo', models.CharField(choices=[('ANUAL', 'Anual (Todo el año)'), ('1C', '1er Cuatrimestre'), ('2C', '2do Cuatrimestre'), ('VERANO', 'Intensivo Verano')], default='ANUAL', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('docente', models.ForeignKey(blank=True, limit_choices_to={'rol': 'DOCENTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comisiones_a_cargo', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comisiones', to='academico.curso')),
            ],
            options={
                'verbose_name_plural': 'Comisiones',
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Parcial 1, TP Final', max_length=100)),
                ('fecha', models.DateTimeField(help_text='Fecha y hora del examen/entrega')),
                ('es_entrega', models.BooleanField(default=False, help_text='Si es True, es un TP para entregar. Si es False, es un examen presencial.')),
                ('temas', models.TextField(blank=True, help_text='Contenidos a evaluar', null=True)),
                ('es_selectivo', models.BooleanField(default=False, help_text='Si es True, solo aplica a los alumnos seleccionados. Si es False, es para todos.')),
                ('alumnos_asignados', models.ManyToManyField(blank=True, help_text='Solo necesario si es un examen selectivo (ej: Recuperatorio)', related_name='evaluaciones_asignadas', to=settings.AUTH_USER_MODEL)),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='academico.comision')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miércoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes'), ('SAB', 'Sábado')], max_length=3)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('aula', models.CharField(blank=True, max_length=50, null=True)),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='academico.comision')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('alumno', models.ForeignKey(limit_choices_to={'rol': 'ALUMNO'}, on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to=settings.AUTH_USER_MODEL)),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='academico.comision')),
            ],
            options={
                'verbose_name_plural': 'Inscripciones',
                'unique_together': {('alumno', 'comision')},
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('presente', models.BooleanField(default=False)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='academico.inscripcion')),
            ],
            options={
                'unique_together': {('inscripcion', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('observacion', models.TextField(blank=True, null=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='academico.evaluacion')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='academico.inscripcion')),
            ],
            options={
                'unique_together': {('inscripcion', 'evaluacion')},
            },
        ),
    ]
