# Generated by Django 6.0 on 2026-03-02 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ej: Unidad 1 - Introducción', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Instrucciones o resumen breve', null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='materiales/%Y/%m/')),
                ('enlace', models.URLField(blank=True, help_text='Enlace a recurso externo', null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='academico.comision')),
            ],
        ),
    ]
