# Generated by Django 6.0 on 2026-03-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_anuncio_comentarioanuncio'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='fecha_expiracion',
            field=models.DateTimeField(blank=True, help_text='Si está vacío, es permanente', null=True),
        ),
    ]
