# Generated by Django 6.0 on 2026-03-03 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_anuncio_fecha_expiracion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='docentes_especificos',
            field=models.ManyToManyField(blank=True, related_name='anuncios_recibidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='tipo_audiencia',
            field=models.CharField(choices=[('COMISION', 'Toda la Comisión (Alumnos y Docente)'), ('TODOS_DOCENTES', 'Todos los Docentes (Global)'), ('DOCENTES_ESPECIFICOS', 'Docentes Específicos')], default='COMISION', max_length=30),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='comision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to='academico.comision'),
        ),
    ]
