# Generated by Django 6.0 on 2026-03-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_anuncio_docentes_especificos_anuncio_tipo_audiencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='estado_alumno',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('LIBRE', 'Libre'), ('PROMOCIONADO', 'Promocionado'), ('ABANDONO', 'Abandono')], default='REGULAR', max_length=20),
        ),
    ]
