# Generated by Django 6.0 on 2026-03-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0006_inscripcion_estado_alumno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialestudio',
            name='archivo',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='materiales/%Y/%m/'),
        ),
    ]
