# Generated by Django 6.0 on 2026-01-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='welcome_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
