# Generated by Django 6.0 on 2026-03-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_welcome_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='debe_cambiar_password',
            field=models.BooleanField(default=True),
        ),
    ]
