# Generated by Django 6.0 on 2026-03-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_debe_cambiar_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
    ]
